dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh | bash
notifications:
  slack:
    rooms:
      secure: cAfEs3yfdzLt/5PY0cEDK5TEDN3v7BqK+gF8qjlE+d2HuNfliA2hsHQw8MKUAR1MREuT1de3H/h1wxbY+PjyJR0VO2nnNnkDSM0HlaQoMjKiosm5MibwwQP7+8yt/HW8s95bzTZZX9+FAT5ny/1Tz/6aS/aLdlO2+6WEEuumrDJcgTceAytgpx3KtBgqtQk3GKwmx6sjJ2tFOcDwjA7tsrU90n6BRJw2EC7R8i07RdvFlnr3TWJKpzpgbZ9y0OVpdjPqXJJhfhW7wGTw51VZk++TblxyRzeTFiBXBUDA1KxE2LOucOD6rP8poard5TwHTqT72bgcIZd1+j6DndJf4NzodKz29YHHY9rD4ALnpGWzVJKFKiavyjYCzqPIBeI8oUOPgriag/pV4vkIHa6l8uDkLzv0vc2+p9YP9aX20DELQo9Lq3oPbMyMl9RETf53bQ0YYnI23cpMnXHBH2Xsd7vrEoiZBq24dFnHYYC6TIB/JrAsC5fZ4I+lzLSH/m/R0LHS4S6Ugzph7ewwIURGLOvklnJTaaq16G/mS/K6lf7kt3jKR9srq3HE7HZKtIGZi8Ihg7ZUIYdVdzPS+SzL0IsGRNrrM7ooEOpfDGy2HodZSEDf89ivwZCijtBcOHDsPbXNVF07hzeboirLpOxtiI3Z4BX7+a4MEUSSJcM11+A=
